name: PE-DeepMHCII
path: models

model:
  emb_size: 16
  conv_size: [9, 11, 13, 15]
  conv_num: [256, 128, 64, 64]
  conv_off: [3, 2, 1, 0]
  dropout: 0.25
  linear_size: [256, 128]
  peptide_pad: 3

padding:
  peptide_len: 21
  peptide_pad: 3
  mhc_len: 34

binding:
  peptide_len: 40
  peptide_pad: 3
  mhc_len: 34

train:
  batch_size: 128
  num_epochs: 20
  opt_params:
    optimizer_cls: Adadelta
    lr: 0.9
    weight_decay: 1e-4

valid:
  batch_size: 128

test:
  batch_size: 128
